### PR TITLE
Add Launch Route On Watch Button

### PR DESCRIPTION
**Pull request by LOOHP**
The previously added button launches into the ETA of the Bus Stop on the watch directly, this new button launches only the route, in case there isn't one particular stop the user wishes to check ETA for but a group of nearby stops on the route.

### CODE REVIEW

**Comment by chunlaw** [comment]
Too narrow...

image

May you consider grouping the buttons into a [menu](https://mui.com/material-ui/react-menu/)?

**Comment by LOOHP** [comment]
Adding a menu for one button seems like an overkill, how about moving the buttons around a little bit? Now it even has the added benefit of slightly larger text.

**Comment by LOOHP** [comment]
Adding a menu for one button seems like an overkill, how about moving the buttons around a little bit? Now it even has the added benefit of slightly larger text as the screen gets wider.

**Comment by chunlaw** [comment]
Sorry this is a "NO" design for me, as it bias to right-handed people.

image

**Comment by LOOHP** [comment]
Alright, continue in #147.

**Pull request closed without merging**
