### PR TITLE
docker, gitlab ci and a change to boardtabbar (scroll) (more changes see commits)

### PR DESCRIPTION
**Pull request by sdip15fa**
added docker & gitlab ci; modified the boardTabBar to make it scroll when overflow (on small screens the width might not be enough to show all the tabs, especially when using english)

### CODE REVIEW

**Comment by hk-ng** [comment]
Using docker image node:latest will be a very bad idea

**Comment by sdip15fa** [comment]
> Using docker image node:latest will be a very bad idea

so use 17 or 18 instead?

**Comment by hk-ng** [comment]
Also, I think this project serve static page as an output instead of a node js server.

According to github page action, there should be a puppeteer to scan all router and create pre render page. They are required for SEO.

**Comment by sdip15fa** [comment]
> Also, I think this project serve static page as an output instead of a node js server.
> 
> According to github page action, there should be a puppeteer to scan all router and create pre render page. They are required for SEO.

Ok I can add yarn predeploy for a non-dev environment

**Review by chunlaw — APPROVED** [review]

**Pull request merged**
