### PR TITLE
add commit hash, message and link to commit

### PR DESCRIPTION
**Pull request by sdip15fa**
- the button appears only if `process.env.REACT_APP_COMMIT_HASH` exists during build

Screenshot_20220706_223345

### CODE REVIEW

**Comment by hk-ng** [comment]
Use commit hash as version number is nonsense to any end user
I would recommend to use 
[Semantic Versioning](https://semver.org/spec/v2.0.0.html)

**Comment by sdip15fa** [comment]
> Use commit hash as version number is nonsense to any end user
> I would recommend to use
> [Semantic Versioning](https://semver.org/spec/v2.0.0.html)

That would mean we need to change the version in package.json frequently, or else we can't distinguish between versions (I added this mostly for debugging perpose

How about hash (vx.x.x)?

**Comment by sdip15fa** [comment]
@chunlaw would you implement the semantic versioning?

**Comment by chunlaw** [comment]
> @chunlaw would you implement the semantic versioning?

pull request is more than welcome

**Comment by sdip15fa** [comment]
Since the version would be read from package.json, it needs to be updated on (literally) every commit.

**Comment by sdip15fa** [comment]
Screenshot_20220708_125335

**Review by chunlaw — CHANGES_REQUESTED** [review]
Looks Great!!

However, not sure whether `.sh` can be run properly in Windows environment. Would there be a workaround?

**Pull request merged**
