### PR TITLE
Better Route Search Remark

### PR DESCRIPTION
**Pull request by LOOHP**
Changes the "route remark" underneath each route in the search screen from the first stop to the difference between itself and the main line. 

***Open to further discussion.***

### CODE REVIEW

**Comment by LOOHP** [comment]
Welcome to review for input.

**Comment by chunlaw** [comment]
image

The idea is very good, while there is small bug. Would you be able to use useMemo to boost the performance as well?

**Comment by LOOHP** [comment]
Sure thing

**Comment by thomas930** [comment]
Any Progress update?

**Comment by pantinker** [comment]
補返 LOOHP 自己寫的解釋：

不如我都解釋清楚啲一次
個PR係用呢個rule compare主線同特別班 
First matching rule applies
如果：
1. 起點不同：寫起點
2. 終點不同：寫終點
3. 有多咗站：寫經...
4. 少咗站：寫不經...

另外如果係嶼巴 會係前面再加埋起點 assuming rule 1 did not already applied

For 經同埋不經
如果所以多咗/少咗嘅站都係連續
會寫 經/不經First至Last
唔係就會寫多咗/少咗嘅第一個同最後一個站
經/不經First及Last

**Comment by LOOHP** [comment]
Superceeded by #182.

**Pull request closed without merging**
