### PR TITLE
UX request: Merge savedOrder to collectionOrder

### PR DESCRIPTION
**Pull request by wulaiyin789**
Please let me know if I'm wrong. Thanks. LOL

Situation:
- Merge saved order to collection order under the setting (常用路線 -> 收藏路線)

Current suggestion:
- Only change the component state without changing the context state
- Only change from UI without affecting the context state

Concerns:
- Coding might be crumby
- Need to add useEffect for each component to synchronize every rendering (Might slightly slow down the performance?)

Testing:
- Need further test. From UIUX perspective, no bug was found atm

## Summary by CodeRabbit

- **New Features**
  - Enhanced collection management with improved index handling and default value appending.
  - Introduced new state management for collections, including conditional rendering and state updates.

- **Bug Fixes**
  - Corrected index calculations and array manipulations to ensure accurate data handling.

- **Improvements**
  - Reorganized imports and improved code clarity in multiple components.
  - Updated drag-and-drop functionality and conditional rendering based on new collection states.

- **Refactor**
  - Adjusted logic in several components to handle new collection state variables and context usage.

### CODE REVIEW

**Comment by chunlaw** [comment]
Seems to be bugged. Clicking the first collection will prompt to "Saved", instead of the first collection

**Comment by wulaiyin789** [comment]
> Seems to be bugged. Clicking the first collection will prompt to "Saved", instead of the first collection

Can you screen-record the bug? Thanks

**Comment by chunlaw** [comment]
> > Seems to be bugged. Clicking the first collection will prompt to "Saved", instead of the first collection
> 
> Can you screen-record the bug? Thanks


https://github.com/hkbus/hk-independent-bus-eta/assets/4438690/83fb7bce-f371-456f-b463-e6d6839895d3

**Comment by chunlaw** [comment]
After reviewing the result, I am not quite get the amendment to the current one.

Might you pm me via Telegram?

**Pull request merged**
