### PR TITLE
Adding a bottom border to MTR and Light Rail

### PR DESCRIPTION
**Pull request by DemChing**
Requested by @pantinker [issue 161](https://github.com/hkbus/hk-independent-bus-eta/issues/161).

1. 現有UI有部份位下面會放"輕鐵"/"港鐵"，因為唔想影響本身有嘅嘢，所以淨係加條薄薄嘅底線就算。

> MTR  LRT

2. 另外仲將啲variable/function寫哂做any嘅typing改返好，有部份@ts-ignore刪咗都冇error嘅都一齊刪埋。

### CODE REVIEW

**Comment by thomas930** [comment]
巴士路線都可以考慮加顏色底線，睇下效果如何? 
輕鐵建議全部黃色底線...

**Comment by pantinker** [comment]
巴士線就唔好加啦，巴士線都加，就變左所有車都有底線，太麻煩了

**Comment by chengkeith** [comment]
黃色底線用 light mode 咪乜都睇唔到🫣

**Comment by chunlaw** [comment]
Sorry to tell you that, this feature distracting me from identifying the route no a lot. I will leave the PR open, see if anyone could suggest an overall UI update on that page.

**Pull request closed without merging**
