### PR TITLE
feat/route search

### PR DESCRIPTION
**Pull request by cswbrian**
Route Search history stored in local storage (max 20 items)
Search history appears only if available

https://user-images.githubusercontent.com/9110909/177186222-85ed382a-0984-4781-a745-ef74818e4d5d.mov

image
image

### CODE REVIEW

**Comment by chunlaw** [comment]
The UI seems so weird to me. How about adding the `Search History` into a separate tab?

Also, device like iPhone 6S shall give very narrow route list, there may be no space to show the routes

**Comment by sdip15fa** [comment]
@cswbrian 
It seems like that the search history is shown when the search query is empty, so we can't scroll through the list of all routes
I agree with @chunlaw that it would be better to implement it in a separate tab

**Comment by cswbrian** [comment]
@sdip15fa 
The current implementation follows the Instagram search history feature.

I don't agree to implement the search history in a separate tab. Search history should appear automatically without any extra click to hint user to re-select recent searches. Having a separate tab will increase the number of clicks and impact user experience. 

Users would enter the search key rather than scrolling the full route list to look up a route.

**Comment by sdip15fa** [comment]
> @sdip15fa The current implementation follows the Instagram search history feature.
> 
> I don't agree to implement the search history in a separate tab. Search history should appear automatically without any extra click to hint user to re-select recent searches. Having a separate tab will increase the number of clicks and impact user experience.
> 
> Users would enter the search key rather than scrolling the full route list to look up a route.

@cswbrian
 I do scroll the full route list sometimes, and I believe some users might find it useful in case they forgot the bus route or don't want to type.

Though I agree that this can improve the ux, this is with sacrifice, so how about implementing it in a separate tab and let users choose whether to enable instagram-like search history?

**Review by chunlaw — APPROVED** [review]

**Pull request merged**
